<?php

return [
    'regions' => [
        "Ağcabədi", 
        "Ağdam", 
        "Ağdaş", 
        "Ağdərə", 
        "Ağstafa", 
        "Ağsu", 
        "Astara", 
        "Bakı", 
        "Balakən", 
        "Beyləqan", 
        "Biləsuvar", 
        "Bərdə", 
        "Cəbrayıl", 
        "Cəlilabad", 
        "Daşkəsən", 
        "Dəliməmmədli", 
        "Fizuli", 
        "Goranboy", 
        "Göyçay", 
        "Göygöl", 
        "Göytəpə", 
        "Gədəbəy", 
        "Gəncə", 
        "Hacıqabul", 
        "Horadiz", 
        "İmişli", 
        "İsmayıllı", 
        "Kürdəmir", 
        "Kəlbəcər", 
        "Laçın", 
        "Lerik", 
        "Liman", 
        "Lənkəran", 
        "Masallı", 
        "Mingəçevir", 
        "Naftalan", 
        "Naxçıvan MR", 
        "Neftçala", 
        "Oğuz", 
        "Qax", 
        "Qazax", 
        "Qobustan", 
        "Quba", 
        "Qubadlı", 
        "Qusar", 
        "Qəbələ", 
        "Saatlı", 
        "Sabirabad", 
        "Şabran", 
        "Salyan", 
        "Şamaxı", 
        "Samux", "Şirvan", 
        "Siyazən", 
        "Sumqayıt", 
        "Şuşa", 
        "Şəki", 
        "Şəmkir", 
        "Tovuz", 
        "Tərtər", 
        "Ucar", 
        "Xaçmaz", 
        "Xaçmaz / Nabran", 
        "Xaçmaz / Xudat", 
        "Xırdalan", 
        "Xızı", 
        "Xocəvənd", 
        "Yardımlı", 
        "Yevlax", 
        "Zaqatala", 
        "Zəngilan", 
        "Zərdab"
    ],
];